# MAS DSE 200: Homework 1 - Python and NumPy

#### Tasks: 

- Introduction to Python and NumPy.  
  
- Submission on Gradescope:
  - Submit this Jupyter notebook to "Homework 1"

#### Due date: Monday 10/4/2021 at 11:59 PM PST

---

Remember: when in doubt, read the documentation first.

Python - https://docs.python.org/3/

NumPy - https://numpy.org/doc/stable/

## Instructions

* You don’t need to explain your approach (unless specified) so please be concise in your submission. 
* To obtain full marks for a question, both the answer and the code should be correct. 
* Completely wrong (or missing) code with correct answer will result in zero marks. 
* Please code the solution in the space provided.

# Author: Matthew Stickle

## Part 1 - Python basics

### 1.  Write a program to swap a float and an int variable and print their data types to verify the swapping operation

* Initialize 2 variables my_int = 5 , and my_float = 1.5
* Swap these variables such that my_int now holds the value of my_float and vice versa
* Verify this by printing their data types 

In [9]:
# COMPLETE THE CELL BELOW 

my_int = 5
my_float = 1.5

print(f"Value of my_int = {my_int}")
print(f"Data type of my_int = {type(my_int)}")
print(f"Value of my_float = {my_float}")
print(f"Data type of my_float = {type(my_float)}")

# Swap the variables
temp = my_int
my_int = my_float
my_float = temp

print(f"Value of my_int = {my_int}")
print(f"Data type of my_int = {type(my_int)}")
print(f"Value of my_float = {my_float}")
print(f"Data type of my_float = {type(my_float)}")

Value of my_int = 5
Data type of my_int = <class 'int'>
Value of my_float = 1.5
Data type of my_float = <class 'float'>
Value of my_int = 1.5
Data type of my_int = <class 'float'>
Value of my_float = 5
Data type of my_float = <class 'int'>


### 2. Write a Python Program to Calculate the area and perimeter of a circle of radius `r`

 $area = \pi r^2$
 
 $perimter = 2 \pi r$
 
 Hint - Use `math.pi` to get the value of $\pi$

In [10]:
# COMPLETE THE CELL BELOW 

import math

def calc_area(r):
    return math.pi * r * r

def calc_perimeter(r):
    return 2 * math.pi * r

def str_to_numeric(a: str):
    if '.' in a:
        return float(a)
    else:
        return int(a)

r = input("Enter radius")
r = str_to_numeric(r)
assert r > 0, f"Must be a valid radius. Cannot calculate area and permiter with r = {r}."

area = calc_area(r)
perimeter = calc_perimeter(r)

print('The area of the circle is %0.2f' % area)
print('The perimeter of the circle is %0.2f' % perimeter)

Enter radius 2


The area of the circle is 12.57
The perimeter of the circle is 12.57


### 3.1 Write a Python function to Check if a Number is divisible by 3

* Complete the function block
* Initialize a variable `num`
* Pass the `num` variable to `is_divisible_by_3` function. Print if the number is divisible by 3
* Hint - A number is divisible by 3 if the sum of the digits is divisible by 3. Implement this check

In [13]:
# COMPLETE CELL BELOW

def is_divisible_by_3(n):
    tot = sum([int(c) for c in str(n)])
    return True if tot % 3 == 0 else False
    
num = input("Enter number")
num = str_to_numeric(num)
if isinstance(num, float):
    # Round float to int before checking if divisible by 3
    num = int(round(num))
a = is_divisible_by_3(num)
assert a == (num % 3 == 0), f"is_divisible_by_3 gave {a} for {num}."
print(f"{num} divisible by 3? {str(a)}")

Enter number 13639452


13639452 divisible by 3? True


### 3.2. Write a Python function to Check if a Number is divisible by 2

* Complete the function block
* Initialize a variable `num`
* Pass the `num` variable to `is_divisible_by_2` function. Print if the number is divisible by 2

In [30]:
# COMPLETE CELL BELOW

def is_divisible_by_2(n):
    # Complete this function
    return True if n % 2 == 0 else False

# Check if the number is divisible by 2
num = input("Enter number")
num = str_to_numeric(num)

# Check if the number is divisible by 2
print(f"{num} divisible by 2? {is_divisible_by_2(num)}")

Enter number 65


65 divisible by 2? False


### 3.3. Write a Python function to Check if a Number is divisible by 6

* Complete the function block
* Initialize a variable `num`
* Pass the `num` variable to `is_divisible_by_6` function. Print if the number is divisible by 6
* Hint - A number is divisible by 6 if it is divisible by both 2 and 3. Use the previously defined functions to check for this.

In [31]:
# COMPLETE CELL BELOW
def is_divisible_by_6(n):
    # Complete this function
    return is_divisible_by_2(n) and is_divisible_by_3(n)

# Check if the number is divisible by 6
num = input("Enter number")
num = str_to_numeric(num)

# Check if the number is divisible by 6
print(f"{num} divisible by 6? {is_divisible_by_6(num)}")

Enter number 64


64 divisible by 6? False


### 4. Write a Python Program to Check if a number has exactly 3 digits(no zeros allowed at the beginning)

* Initialize a variable `num`
* Check and print if the number has 3 digits(no zeros allowed at the beginning)

In [14]:
# COMPLETE THE CELL BELOW 
def count_digits(num: str):
    '''
    1. convert string number to int/float to check if valid number
    2. Check first index of number to make sure 0 is not at the start
    3. Count all instance of a digit: set(0123456789)
    Note: Accept floats to be checked since digit definition does not exclude a float
    the only requirement is that the number does not start with a 0
    '''
    digits = set('0123456789')
    num = str_to_numeric(num) # convert to str or float to make sure number is valid
    num = str(num)
    if num[0] == '0':
        raise ValueError(f"{num} not allowed to start with a 0")
    tot = len([int(c) for c in num if c in digits])
    return True if tot == 3 else False

num = input("Enter number")

print(f"{num} has exactly 3 digits? {count_digits(num)}")

# Check if the number has exactly 3 digits

Enter number 123


123 has exactly 3 digits? True


### 5. Write a Python Program to Check Whether a string is palindrome or not

* Initialize a string
* Lower case it to allow easy comparison - Use `my_str.lower()`
* Check using if-else statements if the string is a palindrome 
* A palindrome is a string which is same read forward or backwards.
* Alternatively, use the [`extended slice`](https://docs.python.org/3/whatsnew/2.3.html#extended-slices) syntax to reverse a string and check for palindrome

In [6]:
# COMPLETE CELL BELOW 

def is_palindrome(my_str: str):
    return my_str.lower() == my_str.lower()[::-1]

my_str = 'aIbohPhoBiA' # change this value for a different output
print(f"{my_str} is a palindrome: {is_palindrome(my_str)}")

my_str = 'aIbohPhoBiA'
assert is_palindrome(my_str[:-2]) == False # Assert that slice of aibohphobia is not a palindrome
assert is_palindrome('RaceCar') == True # Assert that racecar is a palindrome

aIbohPhoBiA is a palindrome: True


### 6.  Print numbers divisible by 5 between 4 and 30, inclusive

* One optimization would be to only generate numbers that are multiples of 5

In [1]:
# COMPLETE THE CELL BELOW 

limit = range(4,31)
for number in limit: # Complete the loop
    if number % 5 == 0:
        print(f"{number} is divisible by 5")
    

5 is divisible by 5
10 is divisible by 5
15 is divisible by 5
20 is divisible by 5
25 is divisible by 5
30 is divisible by 5


### 7. Write a Python Program to print the first n numbers of the Fibonacci series

* Initialize a variable n that denotes the number of elements of the Fibonacci series to be computed
* Use a loop to print the first n numbers of the Fibonacci series 
* Fibonacci series is a recursive series where the `n-th` number in the series is a sum of `n-1`th and `n-2`th element in the series, starting from 0 and 1 

In [3]:
# COMPLETE CELL BELOW
def calc_fib(n: int) -> list:
    '''
    Calculates first n values of the fibonacci series
    Counts 0 and 1 as the first two numbers in series
    '''
    i = 2
    fib = [0, 1]
    while i < n:
        a = fib[-1] + fib[-2]
        fib.append(a)
        i = i + 1
    return fib

n = 5
print(f"First n numbers of fibonacci series are: {calc_fib(n)}")

# Test case: assert calc_fib calculates 50th value correctly
n = 50
a = calc_fib(n)
assert a[-1] == 7778742049, f"Expected 7778742049, found {a[-1]}"

First n numbers of fibonacci series are: [0, 1, 1, 2, 3]


### 8. Write a Python Program that defines a function to Remove consonants From a String

* You can initialize a string of your choice 
* Define the function 
* Use a for loop to remove consonants(any letter other than a,e,i,o,u)

In [14]:
# COMPLETE THE CELL BELOW 

def removeConsonants(s:str) -> str: # Complete the function
    consonants = set('bcdfghjklmnpqrstvwxyz')
    s = s.lower()
    return "".join([l for l in s if l not in consonants])

my_str = "Hello, how are you?. I hope you are doing well."

print(removeConsonants(my_str))

eo, o ae ou?. i oe ou ae oi e.


### 9. Define a function that takes two numbers as arguments and returns the sum of all numbers between the arguments passed (exclusive)

* You can define a range of your choice
* Define the function 
* Use a for loop to add numbers within the range(exclusive)
* Hint - You can also use the formula $1 + 2 + ... + n = \frac{n(n + 1)}{2}$

In [27]:
# COMPLETE THE CELL BELOW 

def sumRange(a, b): # Complete the function using a for loop and range
    sum = 0
    for num in range(a+1,b):
        sum = sum + num
    return sum

def hint(a,b):
    return (((b - 1) * b) / 2) - ((a * (a + 1)) / 2)

    
a = 5
b = 10
total = sumRange(a, b)
print("Result is", total)
print(hint(a,b))

Result is 30
30.0


### 10. Define a class named Triangle that can defines the methods `area` and `perimeter`

* The class can be constructed by the length of the sides. Hint - As arguments of `__init__`
* $area = \sqrt{(s(s-a)(s-b)(s-c)}$ where $s=\frac{(a+b+c)}{2}$ is the semi-perimeter
* $perimeter = a +  b + c$
* **Optional** - If there are repeated calls to the `area` and the `perimeter` functions, how would you optimize the code?

In [16]:
# COMPLETE CELL BELOW
import math

class Triangle:
    def __init__(self, a, b, c):
        self.a = a
        self.b = b
        self.c = c
    
    def perimeter(self):
        return self.a + self.b + self.c
    
    def area(self):
        s = self.perimeter() / 2
        return math.sqrt(s * (s - self.a) * (s - self.b) * (s - self.c))
    
tri = Triangle(3, 4, 5)
print(f"perimeter: {tri.perimeter():.2f} area: {tri.area():.2f}")

perimeter: 12.00 area: 6.00


## Part 2 - NumPy

In [23]:
import numpy as np

### 11. Random array

Generate an integer random numpy array, A, of shape (6,6) with elements from 12 to 22(inclusive). Print the generated random array. (Hint: Look at the documentation of `numpy.random.randint`)

In [24]:
A = np.random.randint(low=12, high=23, size=[6,6])
print(A)

[[17 22 13 12 17 14]
 [19 12 20 19 12 18]
 [19 20 15 15 15 21]
 [17 20 21 14 12 13]
 [16 20 12 14 14 22]
 [21 13 22 21 13 20]]


### 12. Transpose and inverse of the array `A` 

Print the transpose and inverse of A.

In [25]:
print(f"Transpose:\n{A.T}")
print(f"Inverse:\n{np.linalg.inv(A)}")

Transpose:
[[17 19 19 17 16 21]
 [22 12 20 20 20 13]
 [13 20 15 21 12 22]
 [12 19 15 14 14 21]
 [17 12 15 12 14 13]
 [14 18 21 13 22 20]]
Inverse:
[[ 1.42250531e-01 -4.72399151e+00  2.29299363e-01 -2.76008493e-02
  -2.72823779e-01  4.22929936e+00]
 [ 1.88959660e-01 -3.97664544e+00 -4.26751592e-01  9.76645435e-02
   2.34607219e-01  3.57324841e+00]
 [-3.31917905e-01  5.68931352e+00  4.64968153e-01  6.44019816e-02
  -1.96744515e-01 -5.20169851e+00]
 [ 4.57891012e-01 -6.67374381e+00 -1.08280255e+00  7.07714084e-04
   5.19815994e-01  6.25053079e+00]
 [-1.67728238e-01  7.31634820e+00  4.01273885e-01 -1.31634820e-01
  -1.85774947e-01 -6.59872611e+00]
 [-2.78839349e-01  3.53857042e+00  4.01273885e-01 -2.05237084e-02
  -7.46638358e-02 -3.26539278e+00]]


### 13. Array slicing
1. Print the first 3 rows of A.

In [26]:
print(A[:3,:])

[[17 22 13 12 17 14]
 [19 12 20 19 12 18]
 [19 20 15 15 15 21]]


2. Print the first 3 columns of A.

In [27]:
print(A[:,:3])

[[17 22 13]
 [19 12 20]
 [19 20 15]
 [17 20 21]
 [16 20 12]
 [21 13 22]]


### 14. Broadcasting

Add this vector `B=[1,2,3,4,5,6]` to all the rows of `A`. (Hint: Use broadcasting)

In [28]:
B = np.arange(1,7)
print(A + B)

[[18 24 16 16 22 20]
 [20 14 23 23 17 24]
 [20 22 18 19 20 27]
 [18 22 24 18 17 19]
 [17 22 15 18 19 28]
 [22 15 25 25 18 26]]


### 15. Reshaping

Add this vector `B=[1,2,3,4,5,6]` to all the columns of `A`. (Hint: Use np.reshape and broadcasting)

In [29]:
B = np.reshape(B, [B.shape[0],1])
print(A + B)

[[18 23 14 13 18 15]
 [21 14 22 21 14 20]
 [22 23 18 18 18 24]
 [21 24 25 18 16 17]
 [21 25 17 19 19 27]
 [27 19 28 27 19 26]]
